package uet.group1.librarymanagement.Entities;

import java.time.LocalDateTime;

/**
 * Entity representing a borrow record: when a user borrows a book and when they return it.
 */
public class BorrowRecord {
    private int id;
    private String userId;
    private int bookId;
    private LocalDateTime borrowDate;
    private LocalDateTime returnDate;  // null if not yet returned

    public BorrowRecord(int id,
                        String userId,
                        int bookId,
                        LocalDateTime borrowDate,
                        LocalDateTime returnDate) {
        this.id = id;
        this.userId = userId;
        this.bookId = bookId;
        this.borrowDate = borrowDate;
        this.returnDate = returnDate;
    }

    // For inserting new records (id will be generated by DB)
    public BorrowRecord(String userId, int bookId, LocalDateTime borrowDate) {
        this(0, userId, bookId, borrowDate, null);
    }

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public int getBookId() {
        return bookId;
    }
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    public LocalDateTime getBorrowDate() {
        return borrowDate;
    }
    public void setBorrowDate(LocalDateTime borrowDate) {
        this.borrowDate = borrowDate;
    }

    public LocalDateTime getReturnDate() {
        return returnDate;
    }
    public void setReturnDate(LocalDateTime returnDate) {
        this.returnDate = returnDate;
    }

    @Override
    public String toString() {
        String ret = (returnDate == null) ? "Not returned" : returnDate.toString();
        return String.format("Record[%d] user='%s', bookId=%d, borrowed=%s, returned=%s",
                id, userId, bookId, borrowDate, ret);
    }
}
